CC = g++
CFLAGS = -std=c++14 -Wall -g -Werror

wordleSolver.out: wordleSolver.o
	$(CC) $(CFLAGS) -o wordleSolver.out wordleSolver.o

wordleSolver.o: wordleSolver.cpp
	$(CC) $(CFLAGS) -c wordleSolver.cpp

